config/routes.rb
InterviewBlog::Application.routes.draw do

  resources :articles, only: [:index, :show]
  resources :comments, only: [:create, :show]

  namespace :admin do
    resources :articles

    get "dashboard", to: "dashboard#index"
  end

  devise_for :users
  root :to => 'articles#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :author, class_name: "User", foreign_key: :user_id
  has_many :comments
  attr_accessible :blurb, :body, :published_on, :title, :views

  scope :available, order("published_on DESC")
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :artcle
  belongs_to :user
  attr_accessible :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  #
  has_many :articles
  has_many :comments
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_filter :check_admin
  # GET /admin/articles
  # GET /admin/articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /admin/articles/1
  # GET /admin/articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /admin/articles/new
  # GET /admin/articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /admin/articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /admin/articles
  # POST /admin/articles.json
  def create
    @article = current_user.articles.new(params[:article])

    respond_to do |format|
      if @article.save

        format.html { redirect_to [:admin, @article], notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/articles/1
  # PUT /admin/articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to [:admin, @article], notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/articles/1
  # DELETE /admin/articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to admin_dashboard_url }
      format.json { head :no_content }
    end
  end

  private
  def check_admin
    redirect_to root_path, notice: "You are not authorized" unless current_user.admin?
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_filter :check_admin
  def index
    @latest_articles = current_user.articles.order("published_on DESC")
  end

  private
  def check_admin
    redirect_to root_path, notice: "You are not authorized" unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.available
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = current_user.comments.new(params[:comment])
    comment.article_id = params[:article_id]
    comment.save
    redirect_to :back, notice: "Saved your comment"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/articles/_form.html.slim
= form_for [:admin, @article] do |f|
  - if @article.errors.any?
    #error_explanation
      h2 = "#{pluralize(@article.errors.count, "error")} prohibited this admin_article from being saved:"
      ul
        - @article.errors.full_messages.each do |message|
          li = message
  .input
    = f.label :title
    = f.text_field :title
  .input
    = f.label :published_on
    = f.text_field :published_on, class: "datepicker"
  .input
    = f.label :blurb
    = f.text_area :blurb
  .input
    = f.label :body
    = f.text_area :body

  .actions = f.submit 'Save'

app/views/admin/articles/edit.html.slim
h1 Editing Article

== render 'form'

= link_to 'Show', @article
'|
= link_to 'Back', admin_articles_path

app/views/admin/articles/index.html.slim
h1 Listing Articles

table
  tr
    th
    th
    th

  - @articles.each do |admin_article|
    tr
      td = link_to 'Show', article
      td = link_to 'Edit', edit_admin_article_path(article)
      td = link_to 'Destroy', article, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Article', new_admin_article_path

app/views/admin/articles/new.html.slim
h1 New Article

== render 'form'

= link_to 'Back', admin_articles_path

app/views/admin/articles/show.html.slim
p#notice = notice

h2= @article.title
p
  strong= "published: #{@article.published_on}"
= @article.body
.actions
  = link_to 'Edit', edit_admin_article_path(@article)
  |  | 
  = link_to 'Back', admin_dashboard_path

app/views/admin/dashboard/index.html.slim
h1 Admin dashboard

h3 Latest Articles
= striped_table do
  tr
    th Title
    th
    th
  - @latest_articles.each do |article|
    tr
      td= link_to article.title, article
      td= link_to "edit", edit_admin_article_path(article)
      td= link_to "delete", admin_article_path(article), method: "delete"
= link_to "Create a new article", new_admin_article_path, class: "btn"

app/views/articles/_article.html.slim
.article
  h3= link_to article.title, article
  p= "by #{article.author.email} on #{article.published_on}"
  p= article.blurb
  = link_to "more", article

app/views/articles/_comment.html.slim
.comment.well
  p
    | from 
    strong= comment.user.email
    |  on 
    strong= comment.created_at
  = comment.body

app/views/articles/_comment_form.html.slim
= form_for @comment do |f|
  legend Add a comment
  = hidden_field_tag "article_id", @article.id
  = f.text_area :body

  div
    = f.submit "Submit", class: "btn"

app/views/articles/index.html.slim
h1 Welcome to Bloggg
= render @articles

app/views/articles/show.html.slim
h1= @article.title
p
  | by 
  strong= @article.author.email
  |  on 
  strong= @article.published_on
= @article.body

.comments
  - if user_signed_in?
    - if @article.comments.any?
      h4 comments
      = render partial: "articles/comment", collection: @article.comments
  - else
    
    h5 
      = link_to "Sign in", new_user_session_path
      |  or 
      = link_to "Sign up", new_user_registration_path
      |  to leave a comment
  = render "articles/comment_form"

app/views/layouts/application.html.slim
doctype html
html
  head
    = stylesheet_link_tag    'application'
    = javascript_include_tag 'application'
    = csrf_meta_tag
  body
    nav
      .container
        #header
          .navbar.navbar-fixed-top
            .navbar-inner
              .container
                a.btn.btn-navbar data-toggle="collapse" data-target=".nav-collapse"
                  span.icon-bar
                  span.icon-bar
                  span.icon-bar
                a.brand href="/" Bloggg
                .nav-collapse
                  ul.nav
                    - if user_signed_in?
                      - if current_user.admin?
                        li
                          = link_to "Admin", admin_dashboard_path
                      li
                        = link_to "Sign out", destroy_user_session_path, method: "delete"
                    - else
                      li
                        = link_to "Sign In", new_user_session_path
                      li
                        = link_to "Sign Up", new_user_registration_path
    section
      .container
        = yield

app/views/pages/home.html.slim
h1 Pages#home
p Find me in app/views/pages/home.html.slim